### PR TITLE
Keeping Dapr up to date with version 1.13.2

### PR DESCRIPTION
**Pull request by salaboy**
Updating Dapr version based on latest release.

### CODE REVIEW

**Comment by abangser** [comment]
Hey @salaboy thanks for the update!

I have run the `fetch-deps` script which actually utilises this change and pushed this as an additional commit to this PR.

I then attempted to build and use the new workflow image locally using the `pipeline-image build load` script. _Note: Merging this PR will automatically build and push a new version of the image for public consumption, this is just for testing the PR before merge._

Unfortunately I ran into a crash loop back off on two components for Dapr:
1. `dapr-operator` has the following errror:
```
time="2024-04-09T09:48:52.649568222Z" level=fatal msg="error running operator: failed to wait for cache sync\nAPI server did not become ready in time: timeout waiting for api server to be ready\nfailed to wait for cache sync\nfailed to retrieve the initial identity certificate: error establishing connection to sentry: context canceled: connection error: desc = \"transport: Error while dialing: dial tcp: lookup dapr-sentry.default.svc.cluster.local on 10.43.0.10:53: no such host\"" instance=dapr-operator-747557fd66-h7sg5 scope=dapr.operator type=log ver=1.13.2
```
2. `dapr-sidecar-injector` has the following error:
```
time="2024-04-09T09:50:01.40640517Z" level=fatal msg="Error running injector: timed out waiting for injector to become ready\nfailed to retrieve the initial identity certificate: error establishing connection to sentry: context canceled: connection error: desc = \"transport: Error while dialing: dial tcp: lookup dapr-sentry.default.svc.cluster.local on 10.43.0.10:53: no such host\"" instance=dapr-sidecar-injector-7685fc4856-578mv scope=dapr.injector type=log ver=1.13.2
```

These appear certificate driven and I do have cert-manager installed, but I wonder if there is something else going on? Happy to pair with you on this if it helps!

**Comment by salaboy** [comment]
@abangser, that is interesting. Did this happen in a new cluster? or did it happen as part of an upgrade from a previous version? I think that if it is an upgrade, you need to make sure that the CRDs are replace

**Comment by salaboy** [comment]
@abangser oh.. I think I know what is happening.. the sentry shouldn't be installed in the default namespace.. why is that happening? All Dapr Components should be installed in the `dapr-system` namespace, that you usually create when you install the helm chart with the --create-namespace option.

**Comment by abangser** [comment]
Weird @salaboy . I see where you think it was deployed to `default` given the failure log. But it isn't in `default`, it is correctly in `dapr-system`:
image

Why would it be trying to connect in default? 🤔

**Comment by salaboy** [comment]
Can you share the steps that you used to see if I can reproduce the issue
in a new kind cluster ?

That is odd

 - Blog: http://salaboy.com <http://salaboy.wordpress.com>
 - Github user: http://github.com/salaboy
 - Twitter: http://twitter.com/salaboy

 - Mauricio "Salaboy" Salatino -

**Comment by abangser** [comment]
Hmmmmmmm this is weird now...

So I think we should merge this as I tested with the following steps and it all worked fine:
```
2024-04-10 14:01  cd kratix
2024-04-10 14:02  g pull
2024-04-10 14:02  make quick-start
2024-04-10 14:12  cd ../kratix-marketplace/dapr
2024-04-10 14:13  g log -1
2024-04-10 14:13  kaf promise.yaml
2024-04-10 14:13  k get ns --context kind-worker -w
2024-04-10 14:14  kx kind-worker
2024-04-10 14:14  k get deploy -n dapr-system -w
```

The failure happened on an existing k3d cluster but one that had never had dapr installed before, so still a bit odd. But as I said before, I think this is passing our test of running against the documented quick start, and these Promises are inherently meant to be customised for organisations and their environments so if someone runs into something in their environment they are welcome to reach out in the [community slack](https://join.slack.com/t/kratixworkspace/shared_invite/zt-2aqdyq16t-geFUqrQgaTFbcBaP1FlY4g) to work through the customisation!

**Pull request merged**
